fix: ep clipping with no ep grads (#1541)
The current EP grad clipping logic assumes that when using EP all of the
norms returned by `torch.nn.utils.get_total_norm` are `DTensor`s. This
assumption can be violated and the subsequent `full_tensor` call can
correspondingly fail in the edge case where the [ep_grad
list](https://github.com/pytorch/torchtitan/blob/eb786b0ab2b5b00dc474af3a3d71f1af69d744e5/torchtitan/distributed/utils.py?plain=1#L408)
is empty, in which case `get_total_norm` returns `tensor(0.)`, a
non-`DTensor`.


https://github.com/pytorch/torchtitan/blob/eb786b0ab2b5b00dc474af3a3d71f1af69d744e5/torchtitan/distributed/utils.py?plain=1#L421-L423

```
File "/app/torchtitan/torchtitan/distributed/utils.py", line 423, in _clip_grad_norm_with_ep
    ).full_tensor()
      ^^^^^^^^^^^
AttributeError: 'Tensor' object has no attribute 'full_tensor'
```

This edge case can occur in PP+EP setups when model uses some fully
dense and some MoE layers (like DSv3), in which case some pp ranks may
not be assigned any MoE layers.

I suppose it is possible that `non_ep_grads` could also be empty, but I
can only imagine this happening in extreme cases, so I did not change
the `non_ep_grads` code.

CC @tianyu-l