fix set_determinism on single gpu (#1983)
**Summary**

Currently, running
`CONFIG_FILE="./torchtitan/models/llama3/train_configs/debug_model.toml"
NGPU=1 CUDA_VISIBLE_DEVICES=0 ./run_train.sh` returns

```
 dim for dim in distinct_seed_mesh_dims if dim in world_mesh.mesh_dim_names
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: argument of type 'NoneType' is not iterable
```

This PR fixes the case for a single GPU or when
world_mesh.mesh_dim_names is None

**Testing**

Added unit test to `tests/unit_tests/test_set_determinism.py`